### Numpy Array Operations

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,10])
print(f"Basic Slicing: {arr[1:4]} ")
print(f"Basic Slicing: {arr[1:8:2]} ")
print(f"Basic Slicing: {arr[-1]} ")

Basic Slicing: [2 3 4] 
Basic Slicing: [ 2  4  6 10] 
Basic Slicing: 10 


### 2d Array

In [11]:
array_2d = np.array([[4, 2, 3], [1, 5, 6], [7, 8, 9]])
print(f"2d array: {array_2d[0][0:2]}")

2d array: [4 2]


In [13]:
print(f"sort of array: {np.sort(array_2d,axis=1)}")

sort of array: [[2 3 4]
 [1 5 6]
 [7 8 9]]


In [14]:
###Filter

In [15]:
even_Numbers = arr[arr%2==0]
print(even_Numbers)

[ 2  4  6 10]


In [18]:
mask = arr>5
print(f"number greater than 5 {arr[mask]}")

number greater than 5 [ 6  7 10]


In [7]:
arr = np.array([1,2,3,4,5,6,7,10])
index = np.where(arr>5)
print(f"index of number greater than 5 {index}")
index = np.where(arr>5,arr*22,arr*2)
print(f"index of number greater than 5 {index}")

index of number greater than 5 (array([5, 6, 7]),)
index of number greater than 5 [  2   4   6   8  10 132 154 220]


### Adding or  removing data

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr3 = np.concatenate((arr1,arr2))
print(arr)



[ 1  2  3  4  5  6  7 10]


### Array compatibility

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print(a.shape == b.shape)

True


In [19]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print(with_new_row)


new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [22]:
arr = np.array([1,2,3])
deleted = np.delete(arr,2)
print(deleted)

[1 2]
